name: CI with Gradle # Github Action에서 보여질 이름.

on:
  push:
    branches: 
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: ☕️ set up JDK 21
          uses: actions/setup-java@v4
          with: 
            java-version: '21'
            distribution: 'temurin' 
            server-id: github
            setting-path: ${{github.workspace}}
        - name: grant execute permission for gradlew
          run: chmod +x gradlew

        - name: build with gradle(without test)
          run: ./gradlew clean build -x test --stacktrace
